Edit wse draft
AtriaStar/Atria pull request #138
Opened 2022-09-05 16:48 UTC by uwlnf

2022-09-11 18:51 UTC, Saalvage requested changes
Mainly reviewed backend and models, but the frontend sure looks like a mess!!

2022-09-11 18:51 UTC, Saalvage commented on Backend/Controllers/AuthenticationController.cs
> +        ChangePassword(user, newPassword.NewPassword);
1. Should not send the duplicate password for no reason
2. Requiring the correct old password should harden security, so we should do it

2022-09-11 18:51 UTC, Saalvage commented on Backend/Controllers/SearchController.cs
> +using Models.DTO;
Redundant

2022-09-11 18:51 UTC, Saalvage commented on Frontend/Pages/Components/AnswerComponent.razor
> +    {
Wrong codestyle

2022-09-11 18:51 UTC, Saalvage commented on Frontend/Pages/Components/AnswerComponent.razor
> +    public Question Question { get; set; } = null!;
Inconsistent, either we're going with `default!` or with `null!`. Idc which one, but not both.

2022-09-11 18:51 UTC, Saalvage commented on Frontend/Pages/Components/CollabModal.razor
> +                @if (_isLoggedIn && Array.Exists(Collabs, c => c.UserId == UserId))
Wrong style again

2022-09-11 18:51 UTC, Saalvage commented on Models/Question.cs
> +{
No

2022-09-11 18:51 UTC, Saalvage commented on Models/WseRights.cs
> +{
Grrr

2022-09-11 19:20 UTC, Saalvage approved these changes
Backend & Model changes approved, largely left the Frontend alone, up to the devs working on it to decide whether the codestyle should be fixed.

2022-09-13 14:13 UTC, JohHub commented
not fully functional but merging anyway because branch got way out of hand

2022-09-13 14:13 UTC, merged